RRF-87: Search Autocomplete
Raizlabs/rr-ios-sdk pull request #11
Opened 2016-10-11 22:53 UTC by arianaantonio

- Added temp API config
- Hooked up autocomplete and search to live data
- Added "brand" to RCHSearchProduct in SDK

2016-10-12 01:10 UTC, KingOfBrian commented
I'm getting `Error getting current user` when going to that screen. There's a chance that there's some UserDefaults configuration that you have set up that is having it work for you. Can you try a fresh install and see if it works? The Client configuration workaround isn't getting triggered because it's missing.

2016-10-12 01:14 UTC, KingOfBrian commented on Demo/RCHSearchViewController.swift
> +    var autocompleteArray: [String] = []
Don't include the type in the variable name. I'd use something like `products` and `autocompleteSuggestions`

2016-10-12 01:16 UTC, KingOfBrian commented on Demo/RCHSearchViewController.swift
> +                let range: Range<String.Index> = autocompleteString.range(of: searchString)!
I got a crash on this a few times, not entirely sure what I was doing differently

2016-10-12 01:23 UTC, KingOfBrian commented on Demo/RCHSearchViewController.swift
> +                let range: Range<String.Index> = autocompleteString.range(of: searchString)!
Typing fast seems to crash it. I think `searchString` is updated faster than the response.

2016-10-13 00:49 UTC, KingOfBrian commented
You have a merge conflict @arianaantonio ! Also, The status bar should be updated to white inside the search app.

2016-10-13 13:38 UTC, KingOfBrian commented
Looks good @arianaantonio !
One thing we should probably do is put a 0.5 second delay on triggering both requests so we don't bog the system down. These can be triggered via timer in didSet on `searchTerm`.

 A few polish suggestions to take the pattern we talked about further: (#pp)
- Order the methods / vars -- State Management, API Calls, IBActions, UI Delegates.
   - I like to have my IBActions and UI Delegates just modify VC state or trigger API calls, and not have any conditionals or direct view modification. This isn't an absolute, a few small things is fine, but if things get bigger, it's best to model.
- Have the `searchTerm` property manage the text in the `UISearchBar`
- Have the attributed string returned in a method like `attributedText(for row: Int) -> NSAttributedString`

2016-10-14 18:09 UTC, KingOfBrian requested changes
Few comments, I think the timer is the only #req item. Looks great!

2016-10-14 18:09 UTC, KingOfBrian commented on Demo/RCHSearchViewController.swift
> +            var _ = Timer.scheduledTimer(timeInterval: 0.5, target: self, selector: #selector(self.searchForProducts), userInfo: nil, repeats: false)
We also want to save the timer and cancel the last one that was submitted so we don't just delay the search, but only do one search 0.5 seconds after the last keypress.

2016-10-14 18:09 UTC, KingOfBrian commented on Demo/RCHSearchViewController.swift
> +    func resetSearch() {
`dismissSearch` may be a better name.

2016-10-14 18:09 UTC, KingOfBrian commented on Demo/RCHSearchViewController.swift
> +            print(error)
We should present an alert if there's an error with the `localizedDescription` of the error as the message.

2016-10-14 18:09 UTC, KingOfBrian commented on Demo/RCHSearchViewController.swift
> +        }
This entire behavior can get pushed into `searchTerm.didSet` I think.

2016-10-14 18:09 UTC, KingOfBrian commented on Demo/RCHSearchViewController.swift
> +        searchTerm = searchText
Since we're searching as we go, I don't think we have to update the searchTerm here.

2016-10-14 21:08 UTC, arianaantonio commented on Demo/RCHSearchViewController.swift
> +        }
I tried this before but if I move autocomplete into searchTerm.didSet then it gets called when the user selects an autocomplete suggestion as the searchTerm. Which means the autocomplete table pops up over the search results, and we don't want that here.

2016-10-17 18:02 UTC, KingOfBrian commented on Demo/RCHSearchViewController.swift
> +        autocomplete(withQuery: searchText)
I think we might want to do autocomplete on a timer too.

2016-10-17 18:38 UTC, merged