RRF-30: Catalog Screen New
Raizlabs/rr-ios-sdk pull request #6
Opened 2016-09-24 00:36 UTC by arianaantonio

- Added bones of search app in new storyboard
- Built Catalog UI
- Pulling in catalog products from best seller category
- Added AutocompleteBuilder import to SDK

2016-09-24 00:37 UTC, arianaantonio commented
@KingOfBrian Trying this again with a fresh branch created off Master

2016-09-27 16:24 UTC, KingOfBrian requested changes
Hey @arianaantonio -- Reviewed this yesterday but apparently didn't hit submit! Looks good, just a few easy #req fixes.

2016-09-27 16:24 UTC, KingOfBrian commented on Demo/RCHCatalogCollectionViewController.swift
> +        spinner.isHidden = false
#pp Shouldn't need this with `hidesWhenStopped`

2016-09-27 16:24 UTC, KingOfBrian commented on Demo/RCHCatalogCollectionViewController.swift
> +            self.productArray = strategyResponse.recommendedProducts!
#pp I'd convert these `!`'s to a guard statement. If it ever fails it gives a better error message. I try to avoid `!` as much as I can.

2016-09-27 16:24 UTC, KingOfBrian commented on Demo/RichRelevanceSDKDemo/SearchDemo.storyboard
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
#req There are a few duplicate files here. I noticed the a storyboard and a duplicated cell. I'm guessing you moved some files around and missed removing the old ones.

2016-09-27 16:24 UTC, KingOfBrian commented on Demo/RichRelevanceSDKDemo/RCHCatalogCollectionViewController.swift
> +        self.present(storyboard.instantiateViewController(withIdentifier: "rootMenu"), animated: true, completion: nil)
#req We should dismiss here, not present. Otherwise the view controller stack keeps growing.

2016-09-27 16:24 UTC, KingOfBrian commented on Demo/RCHCatalogCollectionViewController.swift
> +        loadData()
We may want to move this to `viewWillAppear` so the list is refreshed every time it comes on screen. I'm not sure if `siteWideBestSellers` adapts with preference though

2016-09-27 16:24 UTC, KingOfBrian commented on Demo/RCHCatalogCollectionViewController.swift
> +    override func didReceiveMemoryWarning() {
#pp I always like to remove any stubs that I'm not actually using.

2016-09-27 16:24 UTC, KingOfBrian commented on Demo/RichRelevanceSDKDemo/RCHCatalogCollectionViewController.swift
> +        let product: RCHRecommendedProduct = productArray[indexPath.row]
#pp you shouldn't need the type annotation on `product`.

2016-09-27 16:26 UTC, KingOfBrian commented
Also -- I checked out the build failure, and I think it just needs a fresh `pod install` to add a new file.

2016-09-28 17:50 UTC, arianaantonio commented on Demo/RCHCatalogCollectionViewController.swift
> +        spinner.isHidden = false
Ah! Did not know this was a thing.

2016-09-28 22:48 UTC, arianaantonio commented
@KingOfBrian Changes made. Not sure how it works with this new review system, if you have to mark the requested changes as completed, or if we just merge.

2016-09-29 19:25 UTC, KingOfBrian approved these changes

2016-09-29 19:45 UTC, merged